# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=10)),
                ('rep', models.CharField(max_length=8)),
                ('label', models.CharField(max_length=30)),
                ('instruction', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Codes',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=4)),
                ('memval', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Memory',
            },
        ),
        migrations.CreateModel(
            name='Opcodetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrc', models.CharField(max_length=10)),
                ('opcode', models.CharField(max_length=6)),
                ('rs', models.CharField(blank=True, max_length=5)),
                ('rt', models.CharField(blank=True, max_length=5)),
                ('rd', models.CharField(blank=True, max_length=5)),
                ('sa', models.CharField(blank=True, max_length=5)),
                ('func', models.CharField(blank=True, max_length=10)),
                ('variable', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Opcode Table',
            },
        ),
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regnum', models.PositiveIntegerField(default=0)),
                ('regval', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'Registers',
            },
        ),
    ]
