# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0002_auto_20180313_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcodetable',
            name='rs',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
