# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0003_opcodetable_rs'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
