# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0004_codes_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codes',
            name='status',
        ),
    ]
