# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0006_codes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='regnum',
            field=models.IntegerField(default=0),
        ),
    ]
