# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0007_auto_20180319_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codes',
            name='status',
        ),
        migrations.AlterField(
            model_name='registers',
            name='regnum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
