# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0009_remove_registers_regval'),
    ]

    operations = [
        migrations.AddField(
            model_name='registers',
            name='regval',
            field=models.CharField(default='0000000000000000', max_length=16),
        ),
    ]
