# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0010_registers_regval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registers',
        ),
        migrations.AlterField(
            model_name='memory',
            name='memval',
            field=models.CharField(default='00', max_length=2),
        ),
    ]
