# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0011_auto_20180319_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regnum', models.PositiveIntegerField(default=0)),
                ('regval', models.CharField(default='0000000000000000', max_length=16)),
            ],
            options={
                'verbose_name_plural': 'Registers',
            },
        ),
    ]
