# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0012_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='regval',
            field=models.CharField(default='00', max_length=16),
        ),
    ]
