# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0015_auto_20180319_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='register',
            name='regnum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
