# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0022_auto_20180319_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='regnum',
        ),
        migrations.AddField(
            model_name='register',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
