# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0025_register_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='number',
            new_name='regnum',
        ),
    ]
