# Generated by Django 2.0.2 on 2018-03-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0026_auto_20180319_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opcodetable',
            old_name='sa',
            new_name='rt',
        ),
        migrations.RemoveField(
            model_name='opcodetable',
            name='func',
        ),
        migrations.AddField(
            model_name='opcodetable',
            name='imm',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
