# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0027_auto_20180324_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piplnsrcdest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrc', models.CharField(max_length=40)),
                ('dest', models.CharField(max_length=5)),
                ('src1', models.CharField(max_length=5)),
                ('src2', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Pipeline Source Destination',
            },
        ),
        migrations.AlterField(
            model_name='opcodetable',
            name='instrc',
            field=models.CharField(max_length=40),
        ),
    ]
