# Generated by Django 2.0.2 on 2018-03-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0028_auto_20180324_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piplnsrcdest',
            name='dest',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='piplnsrcdest',
            name='src1',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='piplnsrcdest',
            name='src2',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
