# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0029_auto_20180324_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='piplnsrcdest',
            name='instrnum',
            field=models.IntegerField(default=0),
        ),
    ]
