# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0030_piplnsrcdest_instrnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='piplnsrcdest',
            name='label',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piplnsrcdest',
            name='stat',
            field=models.IntegerField(default=0),
        ),
    ]
