# Generated by Django 2.0.2 on 2018-04-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mips', '0032_auto_20180328_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcodetable',
            name='instrnum',
            field=models.IntegerField(default=0),
        ),
    ]
